export const STORAGE_KEYS = {
  THEME: 'theme',
  WORDS: '@vocab-book/words',
  STORAGE_TYPE: '@vocab-book/storage_type',
  WEBDAV_URL: '@vocab-book/webdav_url',
  WEBDAV_USERNAME: '@vocab-book/webdav_username',
  WEBDAV_PASSWORD: '@vocab-book/webdav_password',
  S3_BUCKET: '@vocab-book/s3_bucket',
  S3_ENDPOINT: '@vocab-book/s3_endpoint',
  S3_ACCESS_KEY_ID: '@vocab-book/s3_access_key_id',
  S3_SECRET_ACCESS_KEY: '@vocab-book/s3_secret_access_key',
  S3_REGION: '@vocab-book/s3_region',
  LAST_SYNC_TIME_PREFIX: '@vocab-book/last_sync_',
  SIDEBAR_WIDTH: '@vocab-book/sidebar_width',
  DESKTOP_SIDEBAR_OPEN: '@vocab-book/desktop_sidebar_open',
  SPACE_AUTO_SYNC_PREFIX: '@vocab-book/space_auto_sync_',
  LIST_VIEW_CONFIG: '@vocab-book/list_view_config',
  TTS_PROVIDER: '@vocab-book/tts_provider',
} as const;
